#!/bin/sh

usage="$(README_GEN=1 sh ./boxkit --help)"

cat <<EOF > README.md
# Boxkit
\`\`\`
${usage}
\`\`\`

# Quick start
1. Run \`curl https://raw.githubusercontent.com/mtwtkman/boxkit/main/boxkit | sh -s\`
1. Run \`./box e\`
1. Run \`./box i\`
1. Run \`. ~/.bashrc\` or Re-enter the conatiner
EOF
