name: Run test
on: [push]
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - run: curl -s https://raw.githubusercontent.com/89luca89/distrobox/main/install | sudo sh
      - run: ./script/run-test
